### ISSUE TITLE
Iterate on Professor's Week 9 Feedback

### ISSUE THREAD

**Issue by marco-dm1** [marco-dm1/CS320-Team-M#16]
Later in the week, Professor Conboy will be giving us feedback on our Week 9 deliverables and we will need to iterate on the Section 2 Design documentation in some way.

**Comment by marco-dm1** [comment]
Our Week 9 Deliverables should be graded now. Please review your portion of the design, iterate if needed, and submit a regrade request.

**Comment by himccoder** [comment]
![Image](https://github.com/user-attachments/assets/6f8d3f4b-2204-45e9-8006-16c990b26d3d)
![Image](https://github.com/user-attachments/assets/b2d3c4b0-0d5c-4eef-859a-712c19917046)


I've updated both diagrams with feedback
