### ISSUE TITLE
Team Presentation w/ Customer Interaction - Week 12

### ISSUE THREAD

**Issue by marco-dm1** [marco-dm1/CS320-Team-M#18]

**Comment by marco-dm1** [comment]
Create Team Presentation and complete Customer Interaction. Customer Interaction will be on 11/4/2024 instead of the Midpoint Fair on 11/6/2024.

**Comment by Ronkleinhause** [comment]
functionality of the database, hooks for real time, Q&A/About us page,

**Comment by marco-dm1** [comment]
This will be presented 11/18/2024
