### ISSUE TITLE
Architecture Design - DOCUMENTATION - Week 9

### ISSUE THREAD

**Issue by marco-dm1** [marco-dm1/CS320-Team-M#9]

**Comment by marco-dm1** [comment]
Context Diagrams

**Comment by himccoder** [comment]
[![Image](https://github.com/user-attachments/assets/d606e912-4c43-4ea2-97a4-c1771da99a3a)
![Image](https://github.com/user-attachments/assets/8e4c5fdc-03bb-4c13-ae3c-18b54aa67130)
